# Generated by Django 4.1.3 on 2022-11-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('DEV', 'Development'), ('UI/UX', 'UI/UX Design')], default='DEV', max_length=10),
        ),
    ]
