# Generated by Django 4.2.7 on 2025-02-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('DEV', 'Development'), ('UI/UX', 'UI/UX Design'), ('CV', 'Computer Vision')], default='DEV', max_length=10),
        ),
    ]
